# Generated by Django 3.0.5 on 2020-06-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255, verbose_name='nombre de Autor')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos del Autor')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('web', models.URLField(blank=True, null=True, verbose_name='web')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo electronico')),
                ('estado', models.BooleanField(default=True, verbose_name='Autor Activo/Autor no Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre de la Categoria')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoria Activada/Categoria no Activada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
